// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#include "chat.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace LN_Chat {
      template <typename>
PROTOBUF_CONSTEXPR PublishRoomResponse::PublishRoomResponse(::_pbi::ConstantInitialized) {}
struct PublishRoomResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PublishRoomResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PublishRoomResponseDefaultTypeInternal() {}
  union {
    PublishRoomResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PublishRoomResponseDefaultTypeInternal _PublishRoomResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PublishRoomRequest::PublishRoomRequest(::_pbi::ConstantInitialized) {}
struct PublishRoomRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PublishRoomRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PublishRoomRequestDefaultTypeInternal() {}
  union {
    PublishRoomRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PublishRoomRequestDefaultTypeInternal _PublishRoomRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR HeartBeatResponse::HeartBeatResponse(::_pbi::ConstantInitialized) {}
struct HeartBeatResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatResponseDefaultTypeInternal() {}
  union {
    HeartBeatResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatResponseDefaultTypeInternal _HeartBeatResponse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR HeartBeatRequest::HeartBeatRequest(::_pbi::ConstantInitialized) {}
struct HeartBeatRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBeatRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBeatRequestDefaultTypeInternal() {}
  union {
    HeartBeatRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBeatRequestDefaultTypeInternal _HeartBeatRequest_default_instance_;
}  // namespace LN_Chat
static ::_pb::Metadata file_level_metadata_chat_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_chat_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_chat_2eproto = nullptr;
const ::uint32_t TableStruct_chat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LN_Chat::PublishRoomRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LN_Chat::PublishRoomResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LN_Chat::HeartBeatRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::LN_Chat::HeartBeatResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::LN_Chat::PublishRoomRequest)},
        {8, -1, -1, sizeof(::LN_Chat::PublishRoomResponse)},
        {16, -1, -1, sizeof(::LN_Chat::HeartBeatRequest)},
        {24, -1, -1, sizeof(::LN_Chat::HeartBeatResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::LN_Chat::_PublishRoomRequest_default_instance_._instance,
    &::LN_Chat::_PublishRoomResponse_default_instance_._instance,
    &::LN_Chat::_HeartBeatRequest_default_instance_._instance,
    &::LN_Chat::_HeartBeatResponse_default_instance_._instance,
};
const char descriptor_table_protodef_chat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nchat.proto\022\007LN_Chat\"\024\n\022PublishRoomRequ"
    "est\"\025\n\023PublishRoomResponse\"\022\n\020HeartBeatR"
    "equest\"\023\n\021HeartBeatResponse2\243\001\n\013ChatServ"
    "ice\022J\n\013PublishRoom\022\033.LN_Chat.PublishRoom"
    "Request\032\034.LN_Chat.PublishRoomResponse\"\000\022"
    "H\n\rRoomHeartBeat\022\031.LN_Chat.HeartBeatRequ"
    "est\032\032.LN_Chat.HeartBeatResponse\"\000b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_chat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_chat_2eproto = {
    false,
    false,
    281,
    descriptor_table_protodef_chat_2eproto,
    "chat.proto",
    &descriptor_table_chat_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_chat_2eproto::offsets,
    file_level_metadata_chat_2eproto,
    file_level_enum_descriptors_chat_2eproto,
    file_level_service_descriptors_chat_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_chat_2eproto_getter() {
  return &descriptor_table_chat_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_chat_2eproto(&descriptor_table_chat_2eproto);
namespace LN_Chat {
// ===================================================================

class PublishRoomRequest::_Internal {
 public:
};

PublishRoomRequest::PublishRoomRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:LN_Chat.PublishRoomRequest)
}
PublishRoomRequest::PublishRoomRequest(
    ::google::protobuf::Arena* arena,
    const PublishRoomRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PublishRoomRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LN_Chat.PublishRoomRequest)
}









::google::protobuf::Metadata PublishRoomRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[0]);
}
// ===================================================================

class PublishRoomResponse::_Internal {
 public:
};

PublishRoomResponse::PublishRoomResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:LN_Chat.PublishRoomResponse)
}
PublishRoomResponse::PublishRoomResponse(
    ::google::protobuf::Arena* arena,
    const PublishRoomResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PublishRoomResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LN_Chat.PublishRoomResponse)
}









::google::protobuf::Metadata PublishRoomResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[1]);
}
// ===================================================================

class HeartBeatRequest::_Internal {
 public:
};

HeartBeatRequest::HeartBeatRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:LN_Chat.HeartBeatRequest)
}
HeartBeatRequest::HeartBeatRequest(
    ::google::protobuf::Arena* arena,
    const HeartBeatRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  HeartBeatRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LN_Chat.HeartBeatRequest)
}









::google::protobuf::Metadata HeartBeatRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[2]);
}
// ===================================================================

class HeartBeatResponse::_Internal {
 public:
};

HeartBeatResponse::HeartBeatResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:LN_Chat.HeartBeatResponse)
}
HeartBeatResponse::HeartBeatResponse(
    ::google::protobuf::Arena* arena,
    const HeartBeatResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  HeartBeatResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:LN_Chat.HeartBeatResponse)
}









::google::protobuf::Metadata HeartBeatResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_chat_2eproto_getter, &descriptor_table_chat_2eproto_once,
      file_level_metadata_chat_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace LN_Chat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
